package com.example.course_manag_system.mapper;


import com.example.course_manag_system.dto.request.CourseRequestDto;
import com.example.course_manag_system.dto.response.CourseResponseDto;
import com.example.course_manag_system.entity.Course;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface CourseMapper {

    // instructor is resolved and set separately in the service layer,
    // deleted always starts false for a brand-new course, id is generated by JPA.
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "instructor", ignore = true)
    @Mapping(target = "enrollments", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    Course toCourse(CourseRequestDto dto);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "instructor", ignore = true)
    @Mapping(target = "enrollments", ignore = true)
    @Mapping(target = "deleted", ignore = true)
    void updateEntityFromDto(CourseRequestDto dto, @MappingTarget Course course);

    @Mapping(target = "instructorId", source = "instructor.id")
    @Mapping(target = "instructorName", expression =
            "java(course.getInstructor() != null ? course.getInstructor().getFirstName() + \" \" + course.getInstructor().getLastName() : null)")
    @Mapping(target = "enrolledStudentCount", expression =
            "java(course.getEnrollments() == null ? 0 : course.getEnrollments().size())")
    CourseResponseDto toResponseDto(Course course);
}
